---
- name: Install Percona repo
  shell: rpm -Uvh https://www.percona.com/downloads/percona-release/redhat/percona-release-0.1-3.noarch.rpm
  args: {creates: /etc/yum.repos.d/percona-release.repo}

- name: Remove MySQL libraries
  shell: rpm -e --nodeps mysql-libs
  args: {removes: /usr/lib/mysql/libmysqlclient.so.16}

- name:  Install MySQL package
  yum: name={{ item }} state=present
  with_items: 
   - Percona-Server-server-56
   - Percona-Server-shared-56
   - Percona-Server-client-56
   - Percona-Server-devel-56
   - Percona-Server-56-debuginfo
   - Percona-Server-shared-compat
   - percona-toolkit 
   - MySQL-python
   - jemalloc

- name: Create MySQL temporary directory
  file: path={{ tmpdir }} state=directory mode=0750 owner=mysql group=mysql

- name: Create binary log directory
  file: path={{ logdir }} state=directory mode=0750 owner=mysql group=mysql

- name: Configure my.cnf
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysql

- name: Ensure MySQL is started with chkconfig on
  service: name=mysql state=started enabled=yes
