---
- name: Install Percona repo
  shell: rpm -Uvh https://www.percona.com/downloads/percona-release/redhat/percona-release-0.1-3.noarch.rpm
  args: {creates: /etc/yum.repos.d/percona-release.repo}

- name: Remove MySQL libraries
  shell: rpm -e --nodeps mysql-libs
  args: {removes: /usr/lib/mysql/libmysqlclient.so.16}

- name:  Install MySQL package
  yum: name={{ item }} state=present
  with_items: 
   - Percona-Server-server-56
   - Percona-Server-shared-56
   - Percona-Server-client-56
   - Percona-Server-devel-56
   - Percona-Server-56-debuginfo
   - Percona-Server-shared-compat
   - percona-toolkit 
   - MySQL-python
