---
# Removes base mysql-libs packages that are on default installations. rpm is
# used instead of yum to prevent dependencies such as postfix from being
# removed.
- name: Remove MySQL libraries
  shell: rpm -e --nodeps mysql-libs
  ignore_errors: yes


##### Installation for Percona Server 5.5 and 5.6 using the Percona repository
# Install repository
- name: Install Percona repository
  shell: rpm -Uvh http://www.percona.com/downloads/percona-release/redhat/percona-release-0.1-3.noarch.rpm
  args: {creates: /etc/yum.repos.d/percona-release.repo}
  when: mysql_version == "ps_56" or mysql_version == "ps_55"

# Install server
- name: Install Percona Server 5.6 packages
  yum: name={{ item }} state=present
  with_items: 
   - Percona-Server-server-56
   - Percona-Server-shared-56
   - Percona-Server-client-56
   - Percona-Server-devel-56
   - Percona-Server-56-debuginfo
   - Percona-Server-shared-compat
   - percona-toolkit 
  when: mysql_version == "ps_56"

- name: Install Percona Server 5.5 packages
  yum: name={{ item }} state=present
  with_items: 
   - Percona-Server-server-55
   - Percona-Server-shared-55
   - Percona-Server-client-55
   - Percona-Server-devel-55
   - Percona-Server-55-debuginfo
   - Percona-Server-shared-compat
   - percona-toolkit 
  when: mysql_version == "ps_55"


##### Installation for MySQL 5.5 and 5.6 using the IUS repository
# Install repository
- name: Install ius repository (RHEL 5)
  shell: rpm -Uvh http://dl.iuscommunity.org/pub/ius/stable/Redhat/5/x86_64/ius-release-1.0-14.ius.el5.noarch.rpm
  args: {creates: /etc/yum.repos.d/ius.repo}
  when: (mysql_version == "mysql_55" or mysql_version == "mysql_56") and ansible_distribution == "Red Hat Enterprise Linux" and ansible_distribution_version | int == 5

- name: Install ius repository (RHEL 6)
  shell: rpm -Uvh http://dl.iuscommunity.org/pub/ius/stable/Redhat/6/x86_64/ius-release-1.0-14.ius.el6.noarch.rpm
  args: {creates: /etc/yum.repos.d/ius.repo}
  when: (mysql_version == "mysql_55" or mysql_version == "mysql_56") and ansible_distribution == "Red Hat Enterprise Linux" and ansible_distribution_version | int == 6

- name: Install ius repository (RHEL 7)
  shell: rpm -Uvh http://dl.iuscommunity.org/pub/ius/stable/Redhat/7/x86_64/ius-release-1.0-14.ius.el7.noarch.rpm
  args: {creates: /etc/yum.repos.d/ius.repo}
  when: (mysql_version == "mysql_55" or mysql_version == "mysql_56") and ansible_distribution == "Red Hat Enterprise Linux" and ansible_distribution_version | int == 7

- name: Install ius repository (CentOS 5)
  shell: rpm -Uvh http://dl.iuscommunity.org/pub/ius/stable/CentOS/5/x86_64/ius-release-1.0-14.ius.centos5.noarch.rpm
  args: {creates: /etc/yum.repos.d/ius.repo}
  when: (mysql_version == "mysql_55" or mysql_version == "mysql_56") and ansible_distribution == "CentOS" and ansible_distribution_version | int == 5

- name: Install ius repository (CentOS 6)
  shell: rpm -Uvh http://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/ius-release-1.0-14.ius.centos6.noarch.rpm
  args: {creates: /etc/yum.repos.d/ius.repo}
  when: (mysql_version == "mysql_55" or mysql_version == "mysql_56") and ansible_distribution == "CentOS" and ansible_distribution_version | int == 6

- name: Install ius repository (CentOS 7)
  shell: rpm -Uvh http://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm
  args: {creates: /etc/yum.repos.d/ius.repo}
  when: (mysql_version == "mysql_55" or mysql_version == "mysql_56") and ansible_distribution == "CentOS" and ansible_distribution_version | int == 7

# Install server
- debug: msg="{{ ansible_distribution }} {{ ansible_distribution_version | int }} {{ mysql_version }}"

- name: Install MySQL 5.6 packages
  yum: name={{ item }} state=present
  with_items:
   - mysql56u-server
   - mysql56u-common
   - mysql56u-libs
   - mysql56u
   - mysql56u-devel
   - mysql56u-debuginfo
  when: mysql_version == "mysql_56"

- name: Install MySQL 5.5 packages
  yum: name={{ item }} state=present
  with_items:
   - mysql55-server
   - mysql55-libs
   - mysql55
   - mysql55-devel
   - mysql55-debuginfo
  when: mysql_version == "mysql_55"


##### Install additional MySQL utilities, i.e. memory allocator and python lib
- name: Install MySQL utilities
  yum: name={{ item }} state=present
  with_items: 
   - MySQL-python
   - jemalloc


##### Configure MySQL and filesystem
- name: Create MySQL temporary directory
  file: path={{ tmpdir }} state=directory mode=0750 owner=mysql group=mysql

- name: Create binary log directory
  file: path={{ logdir }} state=directory mode=0750 owner=mysql group=mysql

- name: Create MySQL data directory
  file: path={{ datadir }} state=directory mode=0750 owner=mysql group=mysql

# Configure my.cnf
- name: Configure my.cnf (PS)
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysql
  when: mysql_version == "ps_56" or mysql_version == "ps_55"

- name: Configure my.cnf (MySQL)
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysqld
  when: mysql_version == "mysql_56" or mysql_version == "mysql_55"

# Restart and enable service
- name: Ensure MySQL (PS) is started with chkconfig on
  service: name=mysql state=started enabled=yes
  when: mysql_version == "ps_56" or mysql_version == "ps_55"

- name: Ensure MySQL (MySQL) is started with chkconfig on
  service: name=mysqld state=started enabled=yes
  when: mysql_version == "mysql_56" or mysql_version == "mysql_55"
