---
- name: Configure Standalone Instances
  hosts: mysql_base
  remote_user: ansible
  become: true
  roles:
    - mysql-base

- name: Configure Slaves
  hosts: mysql_slave
  remote_user: ansible
  become: true
  roles:
    - mysql-repl-slave
