---
- name: Configure Standalone Instances
  hosts: mysql_base
  remote_user: ansible
  become: true
  roles:
    - mysql-base

- name: Configure Slaves
  hosts: mysql_slave
  remote_user: ansible
  become: true
  roles:
    - mysql-repl-slave

- name: Configure MMM nodes
  hosts: mmm_node
  remote_user: ansible
  become: true
  roles:
    - mmm-node

- name: Configure MMM managers
  hosts: mmm_manager
  remote_user: ansible
  become: true
  roles:
    - mmm-manager
