---
 - name: Add replication user grants
   mysql_user: name=replicant host={{ ansible_eth1['ipv4']['address'] }} password={{ repl_password }} priv=*.*:"REPLICATION SLAVE" state=present
   delegate_to: "{{ repl_parent }}"

 - name: Check if slave is already configured for replication
   mysql_replication: mode=getslave
   ignore_errors: true
   register: slave_status

 - name: Connect to master
   mysql_replication: mode=changemaster master_host={{ repl_parent }} master_user={{ repl_username }} master_password={{ repl_password }} master_log_file={{ hostvars[repl_parent]['server_id'] }}-{{ hostvars[repl_parent]['name'] }}-bin-log.000001 master_log_pos=4
   when: slave_status|failed
   ignore_errors: true

 - name: Start replication
   mysql_replication: mode=startslave
