---
 - name: Create MySQL temporary directory
   file: path={{ tmpdir }} state=directory mode=0750 owner=mysql group=mysql

 - name: Create binary log directory
   file: path={{ logdir }} state=directory mode=0750 owner=mysql group=mysql

 - name: Configure MySQL binary logging
   template: src=my.cnf.j2 dest=/etc/my.cnf
   notify: restart mysql

 - name: Ensure MySQL is on and started in chkconfig
   service: name=mysql state=started enabled=yes

 - name: Connect to master
   mysql_replication: mode=changemaster master_host={{ hostvars[groups['mysql_master'][0]]['ansible_eth1']['ipv4']['address'] }} master_user=replicant master_password={{ repl_password }} master_log_file={{ hostvars[groups['mysql_master'][0]]['server_id'] }}-{{ hostvars[groups['mysql_master'][0]]['name'] }}-bin-log.000001 master_log_pos=4

 - name: Start replication
   mysql_replication: mode=startslave
