---
- name: Install MMM common packages
  yum: name={{ item }} state=present
  with_items:
   - mysql-mmm

- name: Configure mmm_common.conf
  template: src=mmm_common.conf.j2 dest=/etc/mysql-mmm/mmm_common.conf
